In [1]:
import numpy as np

In [24]:
data = np.load('./result/am_9.npz')
data['error_train_list']

array([0.40751967, 0.3282327 , 0.26492158, 0.2412188 , 0.22016768,
       0.21394644, 0.18771325, 0.15062853, 0.1516299 , 0.14703927,
       0.14571334, 0.14150508, 0.12440996, 0.11499912, 0.11398371,
       0.11263301, 0.11225298, 0.11253403, 0.11106771, 0.10377565,
       0.09895525, 0.10470635, 0.10339896, 0.10162381, 0.10044184,
       0.08839213, 0.08977832, 0.0840501 , 0.08483023, 0.08825524,
       0.08547825, 0.0844128 , 0.08422998, 0.07873291, 0.07515815,
       0.07198078, 0.07337843, 0.07521291, 0.07635349, 0.07367452,
       0.07334729, 0.07950099, 0.07563554, 0.07401398, 0.07014721,
       0.07377515, 0.07192614, 0.06914959, 0.06756777, 0.06562765,
       0.0671752 , 0.06538441, 0.06553085, 0.06006011, 0.05893956,
       0.05643029, 0.05554561, 0.05628308, 0.05543118, 0.05446245,
       0.05523674, 0.05536639, 0.05516951, 0.05527083, 0.06036534,
       0.05755678, 0.05450035, 0.05389545, 0.05302611, 0.05106424,
       0.04967061, 0.05545642, 0.05272726, 0.05227307, 0.05367

In [25]:
data['error_validation_list']

array([0.41180938, 0.33104808, 0.26630224, 0.24217311, 0.22069336,
       0.21432637, 0.18818292, 0.14936892, 0.15017072, 0.1455664 ,
       0.14428117, 0.1399001 , 0.122661  , 0.11308393, 0.11198749,
       0.11076352, 0.11044483, 0.11059685, 0.10909068, 0.10181101,
       0.09701174, 0.10281917, 0.10160374, 0.0998071 , 0.09860204,
       0.08655494, 0.08789881, 0.08199753, 0.08299692, 0.08647619,
       0.08371908, 0.08262718, 0.08239625, 0.0768852 , 0.07325536,
       0.07010942, 0.0716484 , 0.07348809, 0.07478833, 0.07198602,
       0.07140796, 0.07763338, 0.073807  , 0.07214627, 0.06836224,
       0.07198809, 0.07031354, 0.06713249, 0.06561652, 0.06381864,
       0.06525486, 0.06338789, 0.0635135 , 0.0580058 , 0.05713329,
       0.05447275, 0.05366198, 0.05412465, 0.05341977, 0.05263729,
       0.05337255, 0.05350756, 0.05329307, 0.0532723 , 0.05869043,
       0.0558799 , 0.05276676, 0.05205721, 0.05080326, 0.04894607,
       0.04784662, 0.05365841, 0.0506962 , 0.0507071 , 0.05211

In [26]:
data['SB_M1']

array([0.90972676, 0.99269352, 0.99808804, 0.99764441, 0.99913008,
       0.99817201, 0.99841895, 0.99956456, 0.99967679, 0.99979715,
       0.9998677 , 0.99980397, 0.99975135, 0.99956441, 0.99961139,
       0.99974472, 0.99959191, 0.99964213, 0.99966377, 0.99958966,
       0.99946554, 0.9995028 , 0.99952221, 0.9994707 , 0.99940656,
       0.99913251, 0.99909754, 0.99920372, 0.99914199, 0.99895476,
       0.99868961, 0.99886453, 0.99889442, 0.99882297, 0.99816514,
       0.99874147, 0.99913858, 0.99903408, 0.99932991, 0.99907492,
       0.99868135, 0.99873717, 0.99859949, 0.99877872, 0.99872361,
       0.99882603, 0.99869468, 0.99890826, 0.99885679, 0.99881609,
       0.99868906, 0.99846052, 0.99801695, 0.99783765, 0.99789659,
       0.99739558, 0.9983208 , 0.99733718, 0.99844168, 0.99810286,
       0.99835609, 0.99843665, 0.9978497 , 0.99764538, 0.99881533,
       0.99848764, 0.99843095, 0.99812453, 0.99676803, 0.99457782,
       0.99718958, 0.9980968 , 0.99739769, 0.99752785, 0.99612