In [1]:
import numpy as np

In [46]:
data = np.load('sgd_42.npz')
data['error_train_list']

array([2.7358476 , 1.67944413, 1.6660837 , 1.66198153, 1.65934999,
       1.65715954, 1.65534493, 1.65395518, 1.65280453, 1.65174811,
       1.65075667, 1.64983183, 1.64897397, 1.64817965, 1.64744351,
       1.64675976, 1.64612308, 1.6455292 , 1.64497522, 1.64445965,
       1.64398218, 1.64354328, 1.64314377, 1.64278433, 1.6424652 ,
       1.64218603, 1.64194576, 1.64174278, 1.64157497, 1.64143981,
       1.6413346 , 1.64125645, 1.64120248, 1.64116982, 1.64115571,
       1.64115753, 1.64117281, 1.64119929, 1.64123486, 1.64127763,
       1.64132588, 1.64137806, 1.64143281, 1.64148889, 1.64154523,
       1.6416009 , 1.64165507, 1.64170703, 1.64175617, 1.64180198,
       1.64184402, 1.64188193, 1.6419154 , 1.64194417, 1.64196806,
       1.64198688, 1.6420005 , 1.6420088 , 1.64201168, 1.64200904,
       1.64200078, 1.64198679, 1.64196697, 1.64194118, 1.64190926,
       1.64187102, 1.64182627, 1.64177475, 1.64171619, 1.64165027,
       1.64157666, 1.64149497, 1.64140481, 1.64130576, 1.64119

In [47]:
data['error_validation_list']

array([3.07401829, 1.78139851, 1.76190962, 1.75602465, 1.75288341,
       1.75077646, 1.74936865, 1.74837633, 1.74741915, 1.74639271,
       1.74535524, 1.74435826, 1.74342394, 1.74255921, 1.74176545,
       1.7410424 , 1.74038933, 1.73980531, 1.73928917, 1.73883937,
       1.73845403, 1.73813093, 1.73786756, 1.73766118, 1.7375088 ,
       1.7374072 , 1.73735289, 1.73734208, 1.73737071, 1.73743449,
       1.73752899, 1.73764972, 1.73779227, 1.7379524 , 1.73812615,
       1.73830992, 1.73850052, 1.73869522, 1.73889172, 1.73908819,
       1.73928321, 1.73947576, 1.73966516, 1.73985106, 1.74003337,
       1.74021222, 1.74038792, 1.74056093, 1.7407318 , 1.74090116,
       1.74106966, 1.74123799, 1.74140679, 1.74157668, 1.74174823,
       1.7419219 , 1.7420981 , 1.74227713, 1.74245917, 1.74264429,
       1.74283246, 1.7430235 , 1.74321712, 1.74341293, 1.74361039,
       1.74380888, 1.74400766, 1.7442059 , 1.7444027 , 1.74459708,
       1.744788  , 1.74497441, 1.74515521, 1.74532932, 1.74549

In [48]:
data['SB_M1']

array([0.66172455, 0.23124082, 0.21437512, 0.20907819, 0.20692159,
       0.20609201, 0.20598785, 0.20630977, 0.20680395, 0.2073511 ,
       0.2079265 , 0.20852408, 0.20913656, 0.20975554, 0.21037317,
       0.21098295, 0.21157995, 0.21216096, 0.21272441, 0.21327021,
       0.2137994 , 0.21431379, 0.21481548, 0.2153065 , 0.21578852,
       0.21626272, 0.21672972, 0.21718968, 0.21764234, 0.21808718,
       0.2185235 , 0.21895059, 0.21936778, 0.2197745 , 0.22017042,
       0.22055537, 0.22092943, 0.2212929 , 0.22164625, 0.22199013,
       0.22232534, 0.22265275, 0.2229733 , 0.22328798, 0.22359776,
       0.2239036 , 0.22420645, 0.22450717, 0.22480659, 0.22510543,
       0.22540439, 0.22570404, 0.2260049 , 0.22630738, 0.22661184,
       0.22691854, 0.22722766, 0.22753929, 0.22785347, 0.22817012,
       0.22848913, 0.22881028, 0.22913329, 0.22945781, 0.22978342,
       0.23010963, 0.23043588, 0.23076156, 0.23108601, 0.2314085 ,
       0.23172828, 0.23204453, 0.23235645, 0.23266318, 0.23296