In [15]:
import numpy as np 

In [16]:
temp = np.array([1,2,3]).reshape((3,1))

In [17]:
temp3 = temp - temp.T
print(temp3)

[[ 0 -1 -2]
 [ 1  0 -1]
 [ 2  1  0]]


In [23]:
diff = temp.T - temp
print(diff)
snc = np.sinc(1 * diff / np.pi)
print(snc)
print(diff*snc)

[[ 0  1  2]
 [-1  0  1]
 [-2 -1  0]]
[[1.         0.84147098 0.45464871]
 [0.84147098 1.         0.84147098]
 [0.45464871 0.84147098 1.        ]]
[[ 0.          0.84147098  0.90929743]
 [-0.84147098  0.          0.84147098]
 [-0.90929743 -0.84147098  0.        ]]


In [18]:
temp1 = np.tile(temp, (3, 1))
temp2 = np.tile(temp.T, (3, 1))
print(temp1)
print(temp2)

[[1]
 [2]
 [3]
 [1]
 [2]
 [3]
 [1]
 [2]
 [3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [24]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf 

from GenerateData import getDataset_highDim
from neural_network import NN_define
from method_2_high_dim import method_2_w0, method_2

N_train = 20
N_test = 10
d = 3

# import data
x_train, y_train, x_valid, y_valid, x_test, y_test = getDataset_highDim(N_train=N_train, N_test=N_test, d=d)
        
epochs = 100
batch_size = 32
K = 2**10
learning_rate = 0.001

model = NN_define(input_size = d, m_size = K, output_size = 1)
model.compile(loss='mse', 
              optimizer=tf.keras.optimizers.SGD(learning_rate=learning_rate), 
              metrics=['accuracy'])

model.fit(x=x_train, y=y_train, 
          validation_data = (x_valid, y_valid), 
          epochs=epochs, 
          batch_size=batch_size)
pred_train = model.predict(x_train)

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 3)]               0         
                                                                 
 dense (Dense)               (None, 1024)              4096      
                                                                 
 dense_1 (Dense)             (None, 1)                 1025      
                                                                 
Total params: 5,121
Trainable params: 5,121
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/100
1/1 [==============================] - 0s 438ms/step - loss: 4.9870 - accuracy: 0.0000e+00 - val_loss: 6.1398 - val_accuracy: 0.0000e+00
Epoch 2/100
1/1 [==============================] - 0s 18ms/step - loss: 5.3454 - accuracy: 0.0000e+00 - val_loss: 4.9835 - val_accuracy: 0.0000e+00
Epoch 3/100
1/1 [====

In [27]:
print(np.shape(x_train))
print(pred_train)

(20, 3)
[[95.02185 ]
 [95.20201 ]
 [95.13088 ]
 [94.2831  ]
 [94.67556 ]
 [95.33351 ]
 [95.2086  ]
 [94.83574 ]
 [95.35751 ]
 [94.42533 ]
 [95.06394 ]
 [94.742516]
 [94.932   ]
 [95.33333 ]
 [94.95743 ]
 [95.20509 ]
 [95.27781 ]
 [94.47012 ]
 [95.30675 ]
 [95.10079 ]]


In [29]:
print(np.shape(x_valid))

(20, 3)


In [34]:
pred_valid = model.preditc(x_valid)

In [33]:
model.predict(x_valid)

array([[95.32297 ],
       [94.89007 ],
       [95.153854],
       [94.3416  ],
       [95.194626],
       [95.01727 ],
       [94.917244],
       [94.99806 ],
       [95.28735 ],
       [94.67064 ],
       [94.94661 ],
       [95.05948 ],
       [94.36626 ],
       [95.24048 ],
       [95.23312 ],
       [95.06507 ],
       [94.78723 ],
       [94.90286 ],
       [95.109535],
       [95.38812 ]], dtype=float32)

In [30]:
model.predict(x_test)

array([[-0.68138826],
       [ 2.0240035 ],
       [ 4.825358  ],
       [ 4.2098765 ],
       [57.68716   ],
       [67.58807   ],
       [ 6.7628126 ],
       [ 3.1865368 ],
       [ 0.49984813],
       [-1.1722863 ]], dtype=float32)

In [36]:
y = np.array([1,2,3]).reshape((3,1))
px = np.array([4,5,6]).reshape((3,1))
fp = np.sqrt(px) * (y - np.mean(y)) / px
print(fp)

[[-0.5       ]
 [ 0.        ]
 [ 0.40824829]]


In [39]:
x_train = np.array([1,2,3,4,5,6,7,8,9,10]).reshape((5,2))
cov_x = np.cov(x_train.T)
px_train = (np.exp(-1 / 2 * np.sum(np.multiply(x_train.T, cov_x @ x_train.T), axis=0)) * 1 / (
                                (2 * np.pi) ** (d / 2)) / np.sqrt(np.linalg.det(cov_x))).reshape(len(x_train), 1)
print(np.shape(px_train))

(5, 1)


<ipython-input-39-5dd6e688334f>:3: RuntimeWarning: divide by zero encountered in true_divide
  px_train = (np.exp(-1 / 2 * np.sum(np.multiply(x_train.T, cov_x @ x_train.T), axis=0)) * 1 / (
<ipython-input-39-5dd6e688334f>:3: RuntimeWarning: invalid value encountered in true_divide
  px_train = (np.exp(-1 / 2 * np.sum(np.multiply(x_train.T, cov_x @ x_train.T), axis=0)) * 1 / (
