In [5]:
import numpy as np

In [30]:
data = np.load('am_9.npz')
data['error_train_list']

array([0.31643337, 0.23722567, 0.19151154, 0.17281891, 0.15637111,
       0.14298026, 0.13618162, 0.12348434, 0.12209298, 0.11625486,
       0.11043562, 0.10324075, 0.10010069, 0.09816084, 0.09632521,
       0.09498293, 0.09293878, 0.09468582, 0.09197545, 0.09010742,
       0.08606425, 0.08695434, 0.08415421, 0.08158923, 0.08146823,
       0.07763533, 0.07828781, 0.07863744, 0.07747431, 0.07454589,
       0.07343203, 0.07240799, 0.07160759, 0.06895362, 0.06815162,
       0.06619007, 0.06503131, 0.06529067, 0.06623167, 0.06629035,
       0.06570072, 0.06421468, 0.06335825, 0.06401335, 0.06244561,
       0.06287191, 0.06068703, 0.06093775, 0.06141747, 0.06268895,
       0.0610597 , 0.06007291, 0.0618349 , 0.06080476, 0.05996759,
       0.06023062, 0.06014973, 0.05830578, 0.058409  , 0.0583531 ,
       0.05897804, 0.05655516, 0.05667046, 0.05593586, 0.05675533,
       0.05674251, 0.05566977, 0.05436937, 0.05349661, 0.05443792,
       0.05250819, 0.05297815, 0.05111538, 0.05041543, 0.05129

In [31]:
data['error_validation_list']

array([0.30114243, 0.22493637, 0.18019498, 0.16212564, 0.14612023,
       0.13343663, 0.12728917, 0.11479062, 0.11363651, 0.10796721,
       0.10218945, 0.09518532, 0.09241559, 0.09071946, 0.08867147,
       0.08739488, 0.0853693 , 0.08713172, 0.08460891, 0.08284732,
       0.07889594, 0.07961933, 0.07694555, 0.0746645 , 0.07457708,
       0.07082285, 0.07160006, 0.07188806, 0.07084361, 0.06802798,
       0.06690534, 0.06588538, 0.06504261, 0.06257967, 0.0617908 ,
       0.0599658 , 0.05896412, 0.05922938, 0.06004019, 0.06011483,
       0.05956245, 0.05810719, 0.05734518, 0.05789326, 0.05639249,
       0.05669423, 0.05472036, 0.05490088, 0.05529736, 0.05665145,
       0.05513675, 0.05412427, 0.05577221, 0.05481025, 0.05411903,
       0.05439824, 0.05427901, 0.05246699, 0.05258198, 0.05255014,
       0.05314383, 0.05096513, 0.051144  , 0.05048018, 0.05129315,
       0.05120768, 0.05003123, 0.04888895, 0.0481096 , 0.04903604,
       0.04730428, 0.04790236, 0.04587475, 0.04525733, 0.04611

In [32]:
data['SB_M1']

array([0.84224272, 0.94416953, 0.97267787, 0.97794667, 0.97896316,
       0.98044759, 0.9797847 , 0.98102107, 0.98172658, 0.98139338,
       0.9824279 , 0.98240603, 0.98455446, 0.98455133, 0.98550899,
       0.98728492, 0.98930091, 0.98936141, 0.98812533, 0.98794588,
       0.98801368, 0.98737   , 0.9897033 , 0.98984618, 0.99027501,
       0.98962351, 0.99095895, 0.99023703, 0.99062553, 0.99036898,
       0.98997011, 0.99125032, 0.99111022, 0.99180987, 0.99048683,
       0.99127277, 0.99198142, 0.99139721, 0.99066252, 0.99199522,
       0.990918  , 0.99110642, 0.98965775, 0.99089617, 0.99126852,
       0.9907743 , 0.99138248, 0.99146204, 0.99154084, 0.99200195,
       0.99242735, 0.99169213, 0.99146053, 0.99150644, 0.99145918,
       0.99230604, 0.99183029, 0.99134173, 0.99208501, 0.99277386,
       0.99317176, 0.99299285, 0.9926558 , 0.99243302, 0.9926629 ,
       0.99312717, 0.99255515, 0.99295374, 0.99213962, 0.99256528,
       0.99296703, 0.99331046, 0.99307649, 0.99256664, 0.99257